# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-13

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install dotload
        run: curl -sL https://raw.githubusercontent.com/okineadev/dotload/main/install.sh | bash

      # Runs a set of commands using the runners shell
      - name: Clone dotfiles
        run: dotload @okineadev
